# Config settings
title: MemoryBox
baseurl: "/memorybox"

# Search settings
tipue_search:
  include:
    pages: true
    posts: true
  exclude:
    files: [index.md, search.html]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
